EC-CUBE 3.0.18で動作するようにserialize/unserializeを利用しない実装に変更
EC-CUBE/mail-magazine-plugin pull request #71
Opened 2019-06-04 02:39 UTC by junpeko5

## 概要
EC-CUBE 3.0.18で動作するようにserialize/unserializeを利用しない実装に変更しました。

メルマガの配信条件をresializeしてDBに保存していましたが、json形式で保存/取り出しするようにしています。

## 互換性について
旧バージョンのメルマガプラグインからアップデートした場合は、マイグレーション処理でDBに保存しているsearch_dataをjsonに変換する処理を追加しています。

2019-06-10 08:59 UTC, nanasess requested changes

2019-06-10 08:59 UTC, nanasess commented on Controller/MailMagazineHistoryController.php
> +use DateTime;
DateTime の use は不要です

2019-06-10 08:59 UTC, nanasess commented on Controller/MailMagazineHistoryController.php
> +        if ($searchDataArray['pref'] != null) {
`['pref']['id']` まで厳密にチェックしようとすると、これくらい書かないとダメかも。最後の is_numeric() も本来はもうちょっと厳密に書いた方がいいです。
`if (array_key_exists('pref', $searchDataArray) && array_key_exists('id', $searchDataArray['pref'] && is_numeric($searchDataArray['pref']['id'])) {`

2019-06-10 08:59 UTC, nanasess commented on Controller/MailMagazineHistoryController.php
> +        if ($searchDataArray['sex'] != null) {
厳密に id の添字までチェックするには、これくらい書かないといけないかも。
あと、$searchData['sex'] (ArrayCollection) に追加する値は、1件ずつ検索せずに findBy でまとめて検索してしまって良いと思います。
```php
if (array_key_exists('sex', $searchDataArray) && is_array($searchDataArray['sex'])) {
    $searchData['sex'] = $app['eccube.repository.master.sex']->findBy(
         ['id' => array_filter(array_map(function ($value) {
            if (array_key_exists('id', $value)) {
                return $value['id'];
            }
        return false;
    }, $searchDataArray['sex']))]);
}
```

2019-06-10 08:59 UTC, nanasess commented on Controller/MailMagazineHistoryController.php
> +        if ($searchDataArray['customer_status'] != null) {
137行目の処理と同様です

2019-06-10 08:59 UTC, nanasess commented on Controller/MailMagazineHistoryController.php
> +            if ( ! is_array($value) || ! array_key_exists('date', $value)) {
Symfony の構文規約では、 ! の前後にスペースを空けないようにしてください
`if (!is_array($value) || !array_key_exists('date', $value)) {`

2019-06-10 08:59 UTC, nanasess commented on Resource/doctrine/migration/Version201906031100.php
> +            $formDataArray['pref'] = ($formData['pref'] != null) ? $formData['pref']->toArray() : null;
Pref では無かった場合は toArray() が存在せずにシステムエラーになる懸念があるので、 `instanceof` でチェックした方がよいです
`$formDataArray['pref'] = ($formData['pref'] instanceof \Eccube\Entity\Pref) ? $formData['pref']->toArray() : null;`

2019-06-10 08:59 UTC, nanasess commented on Resource/doctrine/migration/Version201906031100.php
> +            $formDataArray['sex'] = array();
こんな感じに書いた方がよいかも
```php
$formDataArray['sex'] = array_filter(array_map(function ($entity) {
    if ($entity instanceof \Eccube\Entity\Sex) {
        return $entity->toArray();
    } else {
       return false;
    }
}, $formData['sex']));
```

2019-06-10 08:59 UTC, nanasess commented on Resource/doctrine/migration/Version201906031100.php
> +            $formDataArray['customer_status'] = array();
39行目と同様です

2019-06-10 08:59 UTC, nanasess commented on Resource/doctrine/migration/Version201906031100.php
> +    {
元に戻す処理は必要かどうか要検討

2019-06-10 08:59 UTC, nanasess commented on Resource/doctrine/migration/Version201906031100.php
> +            return;
エラーを黙殺するのはよくないです

2019-06-10 08:59 UTC, nanasess commented on Service/MailMagazineService.php
> +        $formDataArray['pref'] = ($formData['pref'] != null) ? $formData['pref']->toArray() : null;
Version201906031100 の処理と同様

2019-06-10 08:59 UTC, nanasess commented on Tests/Web/MailMagazineCommon.php
> +        $formData['sex'] = array();
Version201906031100 の処理と同様

2019-06-10 23:30 UTC, chihiro-adachi commented on Controller/MailMagazineHistoryController.php
> +            if ( ! is_array($value) || ! array_key_exists('date', $value)) {
cs fixerかけておいてください
`vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v app/Plugin/MailXXXXX`

2019-06-10 23:30 UTC, chihiro-adachi commented on Form/Type/MailMagazineType.php
> -            ->add('buy_category', 'category', array(
ここ削除してるのは理由あります？

2019-06-11 00:51 UTC, junpeko5 commented on Form/Type/MailMagazineType.php
> -            ->add('buy_category', 'category', array(
使用していないため削除しました。

2019-06-11 01:47 UTC, ryo-endo commented on Resource/doctrine/migration/Version201906031100.php
> +    {
プラグインのダウングレードは想定していないので、戻す処理は不要かと考えています。

2019-06-11 02:08 UTC, junpeko5 commented on Controller/MailMagazineHistoryController.php
> +            if ( ! is_array($value) || ! array_key_exists('date', $value)) {
このコマンドで実行しました。
php vendor/bin/php-cs-fixer fix -v --level=symfony app/Plugin/MailMagazine

2019-06-11 05:26 UTC, nanasess approved these changes

2019-06-11 05:27 UTC, nanasess approved these changes

2019-06-11 05:31 UTC, junpeko5 commented on Controller/MailMagazineHistoryController.php
> +        if ($searchDataArray['pref'] != null) {
厳密にチェックするように修正しました。

2019-06-11 05:32 UTC, junpeko5 commented on Controller/MailMagazineHistoryController.php
> +use DateTime;
削除しました。

2019-06-11 05:32 UTC, junpeko5 commented on Controller/MailMagazineHistoryController.php
> +        if ($searchDataArray['sex'] != null) {
上記指摘内容に修正しました。

2019-06-11 05:33 UTC, junpeko5 commented on Controller/MailMagazineHistoryController.php
> +        if ($searchDataArray['customer_status'] != null) {
厳密にチェックするように修正しました。

2019-06-11 06:55 UTC, junpeko5 commented on Resource/doctrine/migration/Version201906031100.php
> +            return;
PDOインスタンスの取得方法を変更し、try,catchは行わないように修正しました。

2019-06-11 06:56 UTC, junpeko5 commented on Resource/doctrine/migration/Version201906031100.php
> +            $formDataArray['pref'] = ($formData['pref'] != null) ? $formData['pref']->toArray() : null;
instanceofのチェックに差し替えました。

2019-06-11 06:56 UTC, junpeko5 commented on Resource/doctrine/migration/Version201906031100.php
> +            $formDataArray['sex'] = array();
上記指摘内容に修正しました。

2019-06-11 06:57 UTC, junpeko5 commented on Service/MailMagazineService.php
> +        $formDataArray['pref'] = ($formData['pref'] != null) ? $formData['pref']->toArray() : null;
厳密にチェックするように修正しました。

2019-06-11 06:58 UTC, junpeko5 commented on Tests/Web/MailMagazineCommon.php
> +        $formData['sex'] = array();
厳密にチェックするように修正しました。

2019-06-11 07:01 UTC, merged

2019-06-12 00:37 UTC, kazumiiiiiiiiiii commented on Resource/doctrine/migration/Version201906031100.php
> +    private function getPDO()
不要なので削除。